apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minedock.fullname" . }}
  labels:
    {{- include "minedock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minedock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "minedock.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minedock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "minedock.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - java
          args:
            - -Xmx{{ .Values.jvm.memoryMaxMi }}M
            - -Xms{{ .Values.jvm.memoryMinMi }}M
            - -jar
            - server.jar
            - nogui
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: server
              containerPort: 25565
              protocol: TCP
  #        livenessProbe:
  #          httpGet:
  #            path: /
  #            port: http
  #        readinessProbe:
  #          httpGet:
  #            path: /
  #            port: http
          volumeMounts:
            - name: config
              mountPath: /server/eula.txt
              subPath: eula.txt
            - name: config
              mountPath: /server/server.properties
              subPath: server.properties
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          # Probes
          {{- toYaml .Values.server.probes | nindent 10 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
