apiVersion: v1
kind: Service
metadata:
  name: {{ include "minedock.fullname" . }}
  labels:
    {{- include "minedock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: server
      protocol: TCP
      name: server
  selector:
    {{- include "minedock.selectorLabels" . | nindent 4 }}
